server:
  port: ${CORE_SERVICE_PORT:8081}

spring:
  application:
    name: core-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default} # Datasource for MongoDB
  data:
    mongodb:
      # Default uses Docker service name 'core_db'
      uri: mongodb://${MONGO_HOST:core_db}:${MONGO_CORE_PORT:27017}/${MONGO_CORE_DB:healthcare_core}
      auto-index-creation: true

    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

  # RabbitMQ Configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

# Monitoring config
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

---
# Development Profile (local machine, no docker network)
spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      uri: mongodb://localhost:${MONGO_CORE_PORT:27017}/${MONGO_CORE_DB:healthcare_core}
    redis:
      host: localhost

  rabbitmq:
    host: localhost

---
# Cloud Profile (AWS RDS + Mongo Atlas)
spring:
  config:
    activate:
      on-profile: cloud

  data:
    mongodb:
      uri: ${CLOUD_MONGO_URI}
